### ISSUE TITLE
[Question] Shifted text in preview image

### ISSUE THREAD

**Issue by weisJ** [jMonkeyEngine-mirrors/jme-swing-devkit-jayfella-github#1]
In the [preview image](https://camo.githubusercontent.com/c548bded6bc45ac8881caee7866c63c5867961c0/68747470733a2f2f692e696d6775722e636f6d2f743748464835302e706e67) I can see that all text is slightly shifted to the top.

As I am the developer of darklaf I'd appreciate if you could answer some questions:
- Do you use any custom font?
- Which jdk version are you using in the image?
- Are you able to reproduce the shifted font in a minimal example?

If the answer to the third question is yes I'd love if you could create an according issue over at [darklaf](https://github.com/weisJ/darklaf) so I can try to solve it.

**Comment by riccardobl** [comment]
Hello, thank you for reaching out.
I don't have the answers to your questions, since this is a mirror of a deleted personal project. 
The original author left the community, but in this forum thread, you can get in contact with the other people that were involved, or that might be interested to continue the development: https://hub.jmonkeyengine.org/t/plugin-based-jme-devkit/43099/129
There they might be able to answer your questions.

**Comment by weisJ** [comment]
Thank you for the information. I guess this can be closed then.
